import { Team } from '../team.model';
import { Alert } from '../alert.model';
import { AppClient } from '../app-client.model';
import { Banner } from '../banner.model';
import { Champ } from '../champ.model';
import { City } from '../city.model';
import { Country } from '../country.model';
import { Disqualification } from '../disqualification.model';
import { Document } from '../document.model';
import { Game } from '../game.model';
import { GameEvent } from '../game-event.model';
import { GameWish } from '../game-wish.model';
import { League } from '../league.model';
import { Pitch } from '../pitch.model';
import { Player } from '../player.model';
import { PlayerInGame } from '../player-in-game.model';
import { PlayerInStage } from '../player-in-stage.model';
import { PlayerInTeam } from '../player-in-team.model';
import { Post } from '../post.model';
import { Role } from '../role.model';
import { Season } from '../season.model';
import { Stadium } from '../stadium.model';
import { Stage } from '../stage.model';
import { StageEvent } from '../stage-event.model';
import { Tag } from '../tag.model';
import { TeamInStage } from '../team-in-stage.model';
import { TransferRequest } from '../transfer-request.model';
import { User } from '../user.model';
import { AbstractModel } from '../base/abstract.model';
import { PostLike } from '../post-like.model';
import { Shirt } from '../shirt.model';

export const createModelByName = (entityName: string): AbstractModel => {
  if (entityName == 'Alert') return new Alert();
  if (entityName == 'Appclient') return new AppClient();
  if (entityName == 'Banner') return new Banner();
  if (entityName == 'Champ') return new Champ();
  if (entityName == 'City') return new City();
  if (entityName == 'Country') return new Country();
  if (entityName == 'Disqualification') return new Disqualification();
  if (entityName == 'Document') return new Document();
  if (entityName == 'Game') return new Game();
  if (entityName == 'GameEvent') return new GameEvent();
  if (entityName == 'GameWish') return new GameWish();
  if (entityName == 'League') return new League();
  if (entityName == 'Pitch') return new Pitch();
  if (entityName == 'Player') return new Player();
  if (entityName == 'PlayerInGame') return new PlayerInGame();
  if (entityName == 'PlayerInStage') return new PlayerInStage();
  if (entityName == 'PlayerInTeam') return new PlayerInTeam();
  if (entityName == 'Post') return new Post();
  if (entityName == 'PostLike') return new PostLike();
  if (entityName == 'Role') return new Role();
  if (entityName == 'Season') return new Season();
  if (entityName == 'Shirt') return new Shirt();
  if (entityName == 'Stadium') return new Stadium();
  if (entityName == 'Stage') return new Stage();
  if (entityName == 'StageEvent') return new StageEvent();
  if (entityName == 'Tag') return new Tag();
  if (entityName == 'Team') return new Team();
  if (entityName == 'TeamInStage') return new TeamInStage();
  if (entityName == 'TransferRequest') return new TransferRequest();
  if (entityName == 'User') return new User();
};
