const { readFileSync, writeFileSync } = require('fs');
const { parse } = require('yaml');

const parsed = parse(readFileSync(__dirname + '/app-schema.yml').toString());

const schemaFileContents  = `// DO NOT EDIT THIS FILE! It is automatically generated
import {SchemaInterface} from "./schema-tools";
export const schema: SchemaInterface  = ` + JSON.stringify(parsed);
writeFileSync(__dirname + '/src/schema.ts', schemaFileContents);


const parsedPages = parse(readFileSync(__dirname + '/pages.yml').toString());
const pagesFileContents  = `// DO NOT EDIT THIS FILE! It is automatically generated
import {PagesInterface} from "./schema-tools";
export const pages: PagesInterface  = ` + JSON.stringify(parsedPages);
writeFileSync(__dirname + '/src/pages.ts', pagesFileContents);