// DO NOT EDIT THIS FILE! It is automatically generated
import { PagesInterface } from './schema-tools';
export const pages: PagesInterface = {
  Appclient: { item: 'Appclient', joins: ['League->Appclient'] },
  League: {
    item: 'League',
    joins: ['Team->League, Country->League', 'Champ->Country', 'Season->Champ', 'Stage->Season'],
  },
  Team: {
    item: 'Team',
    joins: ['PlayerInTeam->Team, Game->Team, TransferRequest->Team, Shirt->Team, PlayerInStage->Team', 'GameEvent->Game, PlayerInGame->Game'],
    full: ['Game', 'Stage', 'Season', 'Champ', 'Country'],
  },
  Player: {
    item: 'Player',
    joins: ['PlayerInTeam->Player, PlayerInGame->Player, TransferRequest->Player, PlayerInStage->Player', 'GameEvent->Game'],
    full: ['Game', 'Stage', 'Season', 'Champ', 'Country'],
  },
  Stage: {
    item: 'Stage',
    joins: ['Game->Stage, StageEvent->Stage, TeamInStage->Stage', 'GameEvent->Game, PlayerInGame->Game'],
  },
  Season: {
    item: 'Season',
    joins: ['Stage->Season', 'Game->Stage, StageEvent->Stage, TeamInStage->Stage', 'GameEvent->Game, PlayerInGame->Game', 'Season->Champ'],
  },
  Champ: { item: 'Champ', joins: ['Season->Champ', 'Stage->Season'] },
  Country: {
    item: 'Country',
    joins: ['Champ->Country', 'Season->Champ', 'Stage->Season'],
  },
  Post: { item: 'Post', joins: ['Tag->Post, PostLike->Post'] },
  Game: {
    item: 'Game',
    joins: ['GameEvent->Game, PlayerInGame->Game, GameWish->Game'],
    full: ['Stage', 'Season', 'Champ', 'Country'],
  },
  Stadium: {
    item: 'Stadium',
    joins: ['Game->Stadium'],
    full: ['Stage', 'Season', 'Champ', 'Country'],
  },
};
